controller:
  image:
    repository: andylippitt/pool_unified
    tag: 0.26

  nodeSelector: {}
  imagePullSecrets: {}
  pullPolicy: IfNotPresent

  service:
    type: NodePort
    nodePort: 31080

proxy:
  image:
    repository: andylippitt/pool_proxy
    tag: 0.21
  
  config:
    ssh: pi@raspberry
    device: "FILE:/dev/ttyS0,b9600,raw"

  nodeSelector: {}
  imagePullSecrets: {}
  pullPolicy: IfNotPresent
